version: "3.8"

services:
  postgres_db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      # Standard port for PostgreSQL databases
      - "5432:5432"
  app:
    depends_on:
      - postgres_db
    build: .
    expose:
      - "8000"
    ports:
      - 8000:8000
    volumes:
      - ./src:/app/src
    command: npm run dev
    environment:
      - DB_URL=postgres://root:root@postgres_db:5432/root
      - PORT=8000
      - OPENAI_API_KEY=<your-openai-api-key>
