version: "3.8"

services:
  postgres_db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - 5432
  app:
    depends_on:
      - postgres_db
    build: .
    expose:
      - ${API_PORT}
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./src:/app/src
    command: npm run dev
    environment:
      - DB_URL=postgres://root:root@postgres_db:5432/root
      - OPENAI_API_KEY=${OPENAI_API_KEY?error}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - PORT=${API_PORT}
